name: Deploy to AWS EC2 Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to AWS EC2 Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        env:
          CI: false

      - name: Copy files to the server
        env:
          AWS_PEM_FILE: ${{ secrets.AWS_PEM_FILE }}
        run: |
          mkdir -p ~/.ssh
          echo "$AWS_PEM_FILE" | tr -d '\r' > ~/.ssh/aws_key.pem
          chmod 600 ~/.ssh/aws_key.pem
          ssh-keyscan -H ec2-13-49-231-136.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts
          sudo rsync -avz --exclude 'node_modules' --exclude '.git' -e "ssh -i ~/.ssh/aws_key.pem" ./build/ ubuntu@ec2-13-49-231-136.eu-north-1.compute.amazonaws.com:/var/www/buzz-frontend/html
